### ISSUE TITLE
JSON Status angle isn't an angle

### ISSUE THREAD

**Issue by EdJoPaTo** [Transport-Protocol/CaDSPracticalExamVS#1]
a 0° to ~180° angle given in a percentage between 0 and 100 should be named "percentage" and not "angle".
Grapper has to be called with "doGrap()" and "doRelease()". There should be no percentage value as status information about it. `{ "grapping":true/false, ... }` would be nice.

**Comment by EdJoPaTo** [comment]
example status message

``` json
{"angle":100,"state":"vertical","type":"GRIPPER_INFO"}
```

**Comment by scimbe** [comment]
agreed! Address this issue in the next update. Thx

**Comment by scimbe** [comment]
Fixed by commit 63ef9aef93a9a4b93289d3a3d2be6d3ea9d0b0eb
Thx

**Comment by EdJoPaTo** [comment]
[procent](http://www.dict.cc/?s=procent) is a denglish word and should be named "percentage" or something like that.

"grap" has still a percentage value that is not very intuitive to use (is 100% grapped open or close? I shouldn't have to ask this question with a well written status message)

possible values for grab: ["open", "closed" ]

While opening or closing the grapper it could send back a "unstable" instead of "open" or "closed" (for values else then 100 or 0)
