### ISSUE TITLE
moveRight() should move clockwise and not counterclockwise

### ISSUE THREAD

**Issue by EdJoPaTo** [Transport-Protocol/CaDSPracticalExamVS#13]
while using `moveRight()` the horizontal axis is moving counterclockwise (but to the right side of the simulation screen).

I would expect `moveRight()` to rotate clockwise.

same problem with `moveLeft()`.

(Simulation, not tested on the robot)

**Comment by scimbe** [comment]
Thanks for this.

Mmmh. Is this a real issue? Anyway, in the first it is important that the robot and the simulation do the same. But perhaps you are right with your interpretation. I will consider this in the next update. 

In the first please let me know if simulation and real system differ in behavior.

**Comment by scimbe** [comment]
Closed ...no code change. Wait for more student info
