### ISSUE TITLE
Grab/ Release does not work as expected

### ISSUE THREAD

**Issue by EdJoPaTo** [Transport-Protocol/CaDSPracticalExamVS#14]
I started the simulation and printed the grap percent to the console.

Then i pressed R (Release?) in the simulation window. The sphere is red, console prints 100.
After pressing G (Grab/p?) in the simulation window the sphere is green, console prints 0.

Now i know this:

```
100 R   Released (Open) Red
0   G   Grabbed (Close) Green
```

now i use doClose()
Expectiation: the sphere turning green and the console prints 0.
Simulation: the sphere stays red, console prints 100.
Roboter: not tested.

**Comment by scimbe** [comment]
Control by keyboard is not officially supported. 
But thx for the report. I will overwork this in-official feature.

**Comment by scimbe** [comment]
Fixed by hauke
