### ISSUE TITLE
Interface for Robot Abstraction

### ISSUE THREAD

**Issue by nos-home** [Transport-Protocol/CaDSPracticalExamVS#18]
Gibt es ein Interface, welches die Funktionalität des Roboters abstrahiert?
Zum Beispiel ein Interface, von dem sich CaDSEV3RobotHAL ableitet?
So wäre es möglich einen Wrapper für CaDSEV3RobotHAL zu bauen.

**Comment by HaukeBu** [comment]
Hi, 
die Klasse CaDSEV3RobotHAL kapselt viele Prozesse die genau in dieser Form ausgeführt werden müssen. Eine Abstraktion/ einen Wrapper kannst du dir ja in jedem Fall selber definieren und CaDSEV3RobotHAL als **Delegate** nutzen. Bei weiteren Fragen gerne das Issue wieder öffnen.
