### ISSUE TITLE
Gripper von Robo 2 + 3 defekt

### ISSUE THREAD

**Issue by S41nts4w** [Transport-Protocol/CaDSPracticalExamVS#19]
Der Gripper von den Robotern 2 und 3 funktioniert nicht.

**Comment by scimbe** [comment]
@hauke there is an alternative error message: "unsupportedOperationException: Remote regulators are not supported"

Perhaps the Hardware get old... Who knows..

**Comment by HaukeBu** [comment]
The gripper components of robot 2 and 3 are repaired and should work (for now) as usual.

@scimbe The mentioned exception could not be reproduced with any of the four robots and the example software. So maybe there are calls at the lejos interface of the robot which are not called via the provided HAL.
