### ISSUE TITLE
VS-Hardware gesucht

### ISSUE THREAD

**Issue by AlexLoeffel** [Transport-Protocol/CaDSPracticalExamVS#20]
an Hauke: 
wir würden ein Ethernet oder Wifi Shield für einen Arduino benötigen (Milestone 3/4).

**Comment by HaukeBu** [comment]
@AlexLoeffel Moin, Arduino Shields für Wifi oder Ethernet haben wir nicht. Wir haben aber Node MCUs, die kann ich euch anbieten. Verbindung zu einem Arduino könnten über ein serielles Interface realisiert werden.

**Comment by AlexLoeffel** [comment]
Ja, ich denke das würde auch gehen. Wir sind Montag bei Martin im Labor. Kann er die mitbringen oder wo kriegen wir die von dir?

**Comment by HaukeBu** [comment]
Moin, wie viele braucht ihr denn? Einen? 
Wir haben nachher Projekttreffen, dann werde ich Martin den mitgeben.

**Comment by AlexLoeffel** [comment]
Ja, nur einen.
Danke
