### ISSUE TITLE
Roboter 2 ist defekt

### ISSUE THREAD

**Issue by fabiansch** [Transport-Protocol/CaDSPracticalExamVS#21]
Moin,

Roboter zwei ist heute nicht an gegangen. Eventuell ist das Netzteil kaputt.

Liebe Grüße,
Fabian

**Comment by HaukeBu** [comment]
Moin, 

ich habe Roboter 2 gerade getestet und der startete problemlos. War es wirklich 2?

Beste Grüße,
Hauke

**Comment by HaukeBu** [comment]
Ich habe jetzt nochmal alle gestartet und konnte keine Probleme feststellen.

**Comment by fabiansch** [comment]
komisch, aber um so besser dass er nun wieder funktioniert. Wir hatten zwar überprüft ob alle Kabel eingesteckt waren, aber vielleicht hatten wir doch etwas übersehen was dann Kommilitonen aufgefallen ist..
