### ISSUE TITLE
Denglish word in status message

### ISSUE THREAD

**Issue by EdJoPaTo** [Transport-Protocol/CaDSPracticalExamVS#3]
[procent](http://www.dict.cc/?s=procent) is a denglish word and should be named "percent", "percentage" or something like that.

**Comment by scimbe** [comment]
Arrg.... Agreed

**Comment by scimbe** [comment]
I am happy for every correction. :-) commit f5bf8f1285fa08854b8a01ce2b20d297ac3f7154
