### ISSUE TITLE
intuitive status message content for grap

### ISSUE THREAD

**Issue by EdJoPaTo** [Transport-Protocol/CaDSPracticalExamVS#4]
"grap" has a percentage value that is not very intuitive to use (is 100% grapped open or close? I shouldn't have to ask this question with a well written status message)

possible values for grab: ["open", "closed" ]

While opening or closing the grapper it could send back a "unstable" instead of "open" or "closed" (for values else then 100 or 0)

**Comment by scimbe** [comment]
Agreed for next milestone

**Comment by scimbe** [comment]
The parameter is maybe useful for future use. For the rest see commit f5bf8f1285fa08854b8a01ce2b20d297ac3f7154
