### ISSUE TITLE
GUI method contain degree in method name and deliver a percentage value

### ISSUE THREAD

**Issue by EdJoPaTo** [Transport-Protocol/CaDSPracticalExamVS#5]
GUI method name `moveVerticalToDegree` and `moveMoveHorizontallyToDegree` deliver a percentage value. Method names should be named `move*ToPercent`.

(And `moveMoveHorizontallyToDegree` should not contain a double 'move' in the name)

**Comment by scimbe** [comment]
Of course, this is caused by the root cause raised up before

**Comment by scimbe** [comment]
Tried to achieve... check it out...commit f5bf8f1285fa08854b8a01ce2b20d297ac3f7154
