### ISSUE TITLE
Grap/ Grapper isn't an english word

### ISSUE THREAD

**Issue by EdJoPaTo** [Transport-Protocol/CaDSPracticalExamVS#7]
should be named grab or grabber...

Another question: what exactly are we building here: [dict.cc/?s=grabber](https://www.dict.cc/?s=grabber)?

**Comment by scimbe** [comment]
That is right. This is a fantasy word created by myself like I created CaDS :-) Running gag. Anyway I am open here...

**Comment by scimbe** [comment]
Fixed by hauke
