### ISSUE TITLE
TestProviderOpenClose

### ISSUE THREAD

**Issue by EdJoPaTo** [Transport-Protocol/CaDSPracticalExamVS#8]
why does the ev3 version is named `TestProviderCloseOpen` and the simulation version `TestProviderOpenClose`?

and why do they do something different:

```
if(on)
  caller.doClose(); 
else
  caller.doOpen();
```

```
if(on)
  caller.doOpen(); // grap
else
  caller.doClose(); // release
```

**Comment by scimbe** [comment]
This is a nit. Anyway we should do it in the same way.... do you like to prove a path?

**Comment by EdJoPaTo** [comment]
[simulation/TestProviderOpenClose.java](https://github.com/Transport-Protocol/CaDSPracticalExamVS/blob/master/src/cads/test/junit/simulation/TestProviderOpenClose.java)
[legoEV3/TestProviderCloseOpen.java](https://github.com/Transport-Protocol/CaDSPracticalExamVS/blob/master/src/cads/test/junit/legoEV3/TestProviderCloseOpen.java)

**Comment by scimbe** [comment]
Hihi ...autocorrection:-) The idea behind the line above was  "do you like to provide a patch" :-)

**Comment by EdJoPaTo** [comment]
provided a patch with Pull Request #10
