### ISSUE TITLE
JSON Status Method access modifier should be private/ protected

### ISSUE THREAD

**Issue by EdJoPaTo** [Transport-Protocol/CaDSPracticalExamVS#9]
Why should I have access to the methods `giveFeedbackByJSonTo` and `onStatusMessage`? The code in the dissassembler looks like a internal helper method: its only fire the event to the class given into the constructor.

That shouldn't be available to the user of `CaDSEV3StudentImplementation` so the methods should be private/ protected?

```
caller = new CaDSEV3StudentImplementation(new CaDSBase(),this,this);
caller.giveFeedbackByJSonTo(data);
caller.onStatusMessage(data);
```

**Comment by scimbe** [comment]
My design :-) I want this wrapper. There is no reason to hide it.
